# Not the latest version, but a stable one I prefer.
version: "3.7"

# Which services (containers) do we want?
services:

  # We give our service (container) a name.
  simulation:
    # Where do we want to build (i.e. where is our Dockerfile).
    build:
      context: server
    # Which command do we want to run inside the container (much like the Dockerfile).
    command: ["python", "main.py"]
    # Actual open the port, mapping from the localhost to inside the container.
    ports:
      - 8888:8888
    # Keep our container running, even in the event of a whole system restart.
    restart: unless-stopped

 # Add other services, DB etc.
 # Add volumes, etc.
